version: '3'
services:
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - "${POSTGRES_PORTS}"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
