version: '3'
services:
  nginx:
    build:
      context: ./devops/nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/app
    command: sh -c "npm run frontend"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/app
    command: sh -c "npm run backend"
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - "${POSTGRES_PORTS}"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
